{"status_code":15,"lang":"python3","run_success":false,"runtime_error":"Line 37: TypeError: [1,3,2] is not valid value for the expected return type list<integer>","full_runtime_error":"TypeError: [1,3,2] is not valid value for the expected return type list<integer>\n    raise TypeError(str(ret) + \" is not valid value for the expected return type list<integer>\");\nLine 37 in _driver (Solution.py)\n    _driver()\nLine 44 in <module> (Solution.py)\nDuring handling of the above exception, another exception occurred:\nTypeError: '<' not supported between instances of 'int' and 'str'\nLine 14 in _serialize_int (./python3/__serializer__.py)\nLine 63 in _serialize (./python3/__serializer__.py)\nLine 48 in <listcomp> (./python3/__serializer__.py)\nLine 48 in serialize_list (./python3/__serializer__.py)\nLine 61 in _serialize (./python3/__serializer__.py)\n    out = ser._serialize(ret, 'list<integer>')\nLine 35 in _driver (Solution.py)","status_runtime":"N/A","memory":16316000,"question_id":"94","elapsed_time":52,"compare_result":"0000000000000000000000000000000000000000000000000000000000000000000000","code_output":"","std_output":"","last_testcase":"[1,null,2,3]","expected_output":"[1,3,2]","task_finish_time":1695430054395,"task_name":"judger.judgetask.Judge","finished":true,"total_correct":0,"total_testcases":70,"runtime_percentile":null,"status_memory":"N/A","memory_percentile":null,"pretty_lang":"Python3","submission_id":"1056717533","status_msg":"Runtime Error","state":"SUCCESS"}